# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_phone_number_new_sms_req import UpdatePhoneNumberNewSmsReq  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdatePhoneNumberNewSmsReq(unittest.TestCase):
    """UpdatePhoneNumberNewSmsReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdatePhoneNumberNewSmsReq(self):
        """Test UpdatePhoneNumberNewSmsReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_phone_number_new_sms_req.UpdatePhoneNumberNewSmsReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
