# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.verify_old_phone_number_req import VerifyOldPhoneNumberReq  # noqa: E501
from swagger_client.rest import ApiException


class TestVerifyOldPhoneNumberReq(unittest.TestCase):
    """VerifyOldPhoneNumberReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyOldPhoneNumberReq(self):
        """Test VerifyOldPhoneNumberReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.verify_old_phone_number_req.VerifyOldPhoneNumberReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
