# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.login_sms_req import LoginSMSReq  # noqa: E501
from swagger_client.rest import ApiException


class TestLoginSMSReq(unittest.TestCase):
    """LoginSMSReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLoginSMSReq(self):
        """Test LoginSMSReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.login_sms_req.LoginSMSReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
