# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OptionalSku(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sku_info': 'str',
        'sku': 'str'
    }

    attribute_map = {
        'sku_info': 'skuInfo',
        'sku': 'sku'
    }

    def __init__(self, sku_info=None, sku=None):  # noqa: E501
        """OptionalSku - a model defined in Swagger"""  # noqa: E501
        self._sku_info = None
        self._sku = None
        self.discriminator = None
        self.sku_info = sku_info
        self.sku = sku

    @property
    def sku_info(self):
        """Gets the sku_info of this OptionalSku.  # noqa: E501

        sku描述  # noqa: E501

        :return: The sku_info of this OptionalSku.  # noqa: E501
        :rtype: str
        """
        return self._sku_info

    @sku_info.setter
    def sku_info(self, sku_info):
        """Sets the sku_info of this OptionalSku.

        sku描述  # noqa: E501

        :param sku_info: The sku_info of this OptionalSku.  # noqa: E501
        :type: str
        """
        if sku_info is None:
            raise ValueError("Invalid value for `sku_info`, must not be `None`")  # noqa: E501

        self._sku_info = sku_info

    @property
    def sku(self):
        """Gets the sku of this OptionalSku.  # noqa: E501

        sku码  # noqa: E501

        :return: The sku of this OptionalSku.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this OptionalSku.

        sku码  # noqa: E501

        :param sku: The sku of this OptionalSku.  # noqa: E501
        :type: str
        """
        if sku is None:
            raise ValueError("Invalid value for `sku`, must not be `None`")  # noqa: E501

        self._sku = sku

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OptionalSku, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OptionalSku):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
