# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.categories import Categories  # noqa: E501
from swagger_client.rest import ApiException


class TestCategories(unittest.TestCase):
    """Categories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategories(self):
        """Test Categories"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.categories.Categories()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
