# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.brand import Brand  # noqa: E501
from swagger_client.rest import ApiException


class TestBrand(unittest.TestCase):
    """Brand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBrand(self):
        """Test Brand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.brand.Brand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
