# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.spu_api import SpuApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSpuApi(unittest.TestCase):
    """SpuApi unit test stubs"""

    def setUp(self):
        self.api = SpuApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_spu_items(self):
        """Test case for get_spu_items

        获取商品列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
