# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_address(self):
        """Test case for add_address

        添加地址  # noqa: E501
        """
        pass

    def test_address_detail(self):
        """Test case for address_detail

        根据id获取地址信息  # noqa: E501
        """
        pass

    def test_address_list(self):
        """Test case for address_list

        获取地址簿列表  # noqa: E501
        """
        pass

    def test_get_user_info(self):
        """Test case for get_user_info

        获取用户基本信息  # noqa: E501
        """
        pass

    def test_remove_address(self):
        """Test case for remove_address

        删除地址  # noqa: E501
        """
        pass

    def test_update_address(self):
        """Test case for update_address

        编辑地址  # noqa: E501
        """
        pass

    def test_update_avatar(self):
        """Test case for update_avatar

        更新用户头像地址  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
