# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.change_cart_selected_req import ChangeCartSelectedReq  # noqa: E501
from swagger_client.rest import ApiException


class TestChangeCartSelectedReq(unittest.TestCase):
    """ChangeCartSelectedReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeCartSelectedReq(self):
        """Test ChangeCartSelectedReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_cart_selected_req.ChangeCartSelectedReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
