# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BrandOrder(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'brand_orders': 'list[IdOrder]'
    }

    attribute_map = {
        'brand_orders': 'brandOrders'
    }

    def __init__(self, brand_orders=None):  # noqa: E501
        """BrandOrder - a model defined in Swagger"""  # noqa: E501
        self._brand_orders = None
        self.discriminator = None
        self.brand_orders = brand_orders

    @property
    def brand_orders(self):
        """Gets the brand_orders of this BrandOrder.  # noqa: E501


        :return: The brand_orders of this BrandOrder.  # noqa: E501
        :rtype: list[IdOrder]
        """
        return self._brand_orders

    @brand_orders.setter
    def brand_orders(self, brand_orders):
        """Sets the brand_orders of this BrandOrder.


        :param brand_orders: The brand_orders of this BrandOrder.  # noqa: E501
        :type: list[IdOrder]
        """
        if brand_orders is None:
            raise ValueError("Invalid value for `brand_orders`, must not be `None`")  # noqa: E501

        self._brand_orders = brand_orders

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BrandOrder, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BrandOrder):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
