# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ListCartsReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'page': 'int',
        'page_size': 'int',
        'orderby': 'str',
        'sort': 'str'
    }

    attribute_map = {
        'page': 'page',
        'page_size': 'page_size',
        'orderby': 'orderby',
        'sort': 'sort'
    }

    def __init__(self, page=None, page_size=15, orderby='cart_id', sort='desc'):  # noqa: E501
        """ListCartsReq - a model defined in Swagger"""  # noqa: E501
        self._page = None
        self._page_size = None
        self._orderby = None
        self._sort = None
        self.discriminator = None
        self.page = page
        self.page_size = page_size
        self.orderby = orderby
        self.sort = sort

    @property
    def page(self):
        """Gets the page of this ListCartsReq.  # noqa: E501

         当前页码  # noqa: E501

        :return: The page of this ListCartsReq.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this ListCartsReq.

         当前页码  # noqa: E501

        :param page: The page of this ListCartsReq.  # noqa: E501
        :type: int
        """
        if page is None:
            raise ValueError("Invalid value for `page`, must not be `None`")  # noqa: E501

        self._page = page

    @property
    def page_size(self):
        """Gets the page_size of this ListCartsReq.  # noqa: E501

         展示数量  # noqa: E501

        :return: The page_size of this ListCartsReq.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this ListCartsReq.

         展示数量  # noqa: E501

        :param page_size: The page_size of this ListCartsReq.  # noqa: E501
        :type: int
        """
        if page_size is None:
            raise ValueError("Invalid value for `page_size`, must not be `None`")  # noqa: E501

        self._page_size = page_size

    @property
    def orderby(self):
        """Gets the orderby of this ListCartsReq.  # noqa: E501

         排序字段,默认 cart_id  # noqa: E501

        :return: The orderby of this ListCartsReq.  # noqa: E501
        :rtype: str
        """
        return self._orderby

    @orderby.setter
    def orderby(self, orderby):
        """Sets the orderby of this ListCartsReq.

         排序字段,默认 cart_id  # noqa: E501

        :param orderby: The orderby of this ListCartsReq.  # noqa: E501
        :type: str
        """
        if orderby is None:
            raise ValueError("Invalid value for `orderby`, must not be `None`")  # noqa: E501

        self._orderby = orderby

    @property
    def sort(self):
        """Gets the sort of this ListCartsReq.  # noqa: E501

         排序方式(asc,desc), 默认 desc  # noqa: E501

        :return: The sort of this ListCartsReq.  # noqa: E501
        :rtype: str
        """
        return self._sort

    @sort.setter
    def sort(self, sort):
        """Sets the sort of this ListCartsReq.

         排序方式(asc,desc), 默认 desc  # noqa: E501

        :param sort: The sort of this ListCartsReq.  # noqa: E501
        :type: str
        """
        if sort is None:
            raise ValueError("Invalid value for `sort`, must not be `None`")  # noqa: E501

        self._sort = sort

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ListCartsReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ListCartsReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
