# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MergeCartsReq(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'carts': 'list[CreateCartsReq]'
    }

    attribute_map = {
        'carts': 'carts'
    }

    def __init__(self, carts=None):  # noqa: E501
        """MergeCartsReq - a model defined in Swagger"""  # noqa: E501
        self._carts = None
        self.discriminator = None
        self.carts = carts

    @property
    def carts(self):
        """Gets the carts of this MergeCartsReq.  # noqa: E501

         需要合并的购物车商品信息  # noqa: E501

        :return: The carts of this MergeCartsReq.  # noqa: E501
        :rtype: list[CreateCartsReq]
        """
        return self._carts

    @carts.setter
    def carts(self, carts):
        """Sets the carts of this MergeCartsReq.

         需要合并的购物车商品信息  # noqa: E501

        :param carts: The carts of this MergeCartsReq.  # noqa: E501
        :type: list[CreateCartsReq]
        """
        if carts is None:
            raise ValueError("Invalid value for `carts`, must not be `None`")  # noqa: E501

        self._carts = carts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MergeCartsReq, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MergeCartsReq):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
