# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SpuItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'row_id': 'int',
        'id': 'str',
        'name': 'str',
        'pic': 'str',
        'price': 'str',
        'sku': 'str',
        'sold': 'str'
    }

    attribute_map = {
        'row_id': 'rowId',
        'id': 'id',
        'name': 'name',
        'pic': 'pic',
        'price': 'price',
        'sku': 'sku',
        'sold': 'sold'
    }

    def __init__(self, row_id=None, id=None, name=None, pic=None, price=None, sku=None, sold=None):  # noqa: E501
        """SpuItem - a model defined in Swagger"""  # noqa: E501
        self._row_id = None
        self._id = None
        self._name = None
        self._pic = None
        self._price = None
        self._sku = None
        self._sold = None
        self.discriminator = None
        self.row_id = row_id
        self.id = id
        self.name = name
        self.pic = pic
        self.price = price
        self.sku = sku
        self.sold = sold

    @property
    def row_id(self):
        """Gets the row_id of this SpuItem.  # noqa: E501

         分页 id  # noqa: E501

        :return: The row_id of this SpuItem.  # noqa: E501
        :rtype: int
        """
        return self._row_id

    @row_id.setter
    def row_id(self, row_id):
        """Sets the row_id of this SpuItem.

         分页 id  # noqa: E501

        :param row_id: The row_id of this SpuItem.  # noqa: E501
        :type: int
        """
        if row_id is None:
            raise ValueError("Invalid value for `row_id`, must not be `None`")  # noqa: E501

        self._row_id = row_id

    @property
    def id(self):
        """Gets the id of this SpuItem.  # noqa: E501

         商品 id  # noqa: E501

        :return: The id of this SpuItem.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SpuItem.

         商品 id  # noqa: E501

        :param id: The id of this SpuItem.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this SpuItem.  # noqa: E501

         商品名称  # noqa: E501

        :return: The name of this SpuItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this SpuItem.

         商品名称  # noqa: E501

        :param name: The name of this SpuItem.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def pic(self):
        """Gets the pic of this SpuItem.  # noqa: E501

         商品图片  # noqa: E501

        :return: The pic of this SpuItem.  # noqa: E501
        :rtype: str
        """
        return self._pic

    @pic.setter
    def pic(self, pic):
        """Sets the pic of this SpuItem.

         商品图片  # noqa: E501

        :param pic: The pic of this SpuItem.  # noqa: E501
        :type: str
        """
        if pic is None:
            raise ValueError("Invalid value for `pic`, must not be `None`")  # noqa: E501

        self._pic = pic

    @property
    def price(self):
        """Gets the price of this SpuItem.  # noqa: E501

         商品价格  # noqa: E501

        :return: The price of this SpuItem.  # noqa: E501
        :rtype: str
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this SpuItem.

         商品价格  # noqa: E501

        :param price: The price of this SpuItem.  # noqa: E501
        :type: str
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def sku(self):
        """Gets the sku of this SpuItem.  # noqa: E501

         价格最低sku码  # noqa: E501

        :return: The sku of this SpuItem.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this SpuItem.

         价格最低sku码  # noqa: E501

        :param sku: The sku of this SpuItem.  # noqa: E501
        :type: str
        """
        if sku is None:
            raise ValueError("Invalid value for `sku`, must not be `None`")  # noqa: E501

        self._sku = sku

    @property
    def sold(self):
        """Gets the sold of this SpuItem.  # noqa: E501

         销量  # noqa: E501

        :return: The sold of this SpuItem.  # noqa: E501
        :rtype: str
        """
        return self._sold

    @sold.setter
    def sold(self, sold):
        """Sets the sold of this SpuItem.

         销量  # noqa: E501

        :param sold: The sold of this SpuItem.  # noqa: E501
        :type: str
        """
        if sold is None:
            raise ValueError("Invalid value for `sold`, must not be `None`")  # noqa: E501

        self._sold = sold

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SpuItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SpuItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
