# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.carts_api import CartsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCartsApi(unittest.TestCase):
    """CartsApi unit test stubs"""

    def setUp(self):
        self.api = CartsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_batch_change_cart_selected(self):
        """Test case for batch_change_cart_selected

        批量设置购物车商品选中状态  # noqa: E501
        """
        pass

    def test_change_cart_selected(self):
        """Test case for change_cart_selected

        设置购物车商品选中状态  # noqa: E501
        """
        pass

    def test_create_carts(self):
        """Test case for create_carts

        添加到商品购物车  # noqa: E501
        """
        pass

    def test_get_cart(self):
        """Test case for get_cart

        获取购物车商品详情  # noqa: E501
        """
        pass

    def test_list_carts(self):
        """Test case for list_carts

        购物车商品列表  # noqa: E501
        """
        pass

    def test_merge_carts(self):
        """Test case for merge_carts

        合并本地购物车商品  # noqa: E501
        """
        pass

    def test_remove_cart(self):
        """Test case for remove_cart

        删除购物车商品  # noqa: E501
        """
        pass

    def test_update_cart(self):
        """Test case for update_cart

        修改购物车商品  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
