# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.category_api import CategoryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoryApi(unittest.TestCase):
    """CategoryApi unit test stubs"""

    def setUp(self):
        self.api = CategoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_categories(self):
        """Test case for categories

        获取类别树形列表  # noqa: E501
        """
        pass

    def test_create_category(self):
        """Test case for create_category

        创建类别  # noqa: E501
        """
        pass

    def test_get_category(self):
        """Test case for get_category

        获取单个类别信息  # noqa: E501
        """
        pass

    def test_get_popular_categories(self):
        """Test case for get_popular_categories

        获取热门类别列表  # noqa: E501
        """
        pass

    def test_update_popular_categories(self):
        """Test case for update_popular_categories

        更新热门类别列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
