# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.product_api import ProductApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProductApi(unittest.TestCase):
    """ProductApi unit test stubs"""

    def setUp(self):
        self.api = ProductApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_brands(self):
        """Test case for brands

        获取品牌列表  # noqa: E501
        """
        pass

    def test_create_brand(self):
        """Test case for create_brand

        创建品牌  # noqa: E501
        """
        pass

    def test_get_brand(self):
        """Test case for get_brand

        获取单个品牌信息  # noqa: E501
        """
        pass

    def test_get_brand_tree(self):
        """Test case for get_brand_tree

        获取品牌列表树形结构  # noqa: E501
        """
        pass

    def test_get_popular_brands(self):
        """Test case for get_popular_brands

        获取热门品牌列表  # noqa: E501
        """
        pass

    def test_get_product(self):
        """Test case for get_product

        """
        pass

    def test_update_brand_order(self):
        """Test case for update_brand_order

        更新热门品牌列表  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
