# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sku_api import SkuApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSkuApi(unittest.TestCase):
    """SkuApi unit test stubs"""

    def setUp(self):
        self.api = SkuApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_item_info(self):
        """Test case for get_item_info

        获取商品详情  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
