# coding: utf-8

"""

    认证服务后台api  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.verify_phone_code_req import VerifyPhoneCodeReq  # noqa: E501
from swagger_client.rest import ApiException


class TestVerifyPhoneCodeReq(unittest.TestCase):
    """VerifyPhoneCodeReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVerifyPhoneCodeReq(self):
        """Test VerifyPhoneCodeReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.verify_phone_code_req.VerifyPhoneCodeReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
