# coding: utf-8

# flake8: noqa

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.customer_api import CustomerApi
from swagger_client.api.group_api import GroupApi
from swagger_client.api.product_api import ProductApi
from swagger_client.api.role_api import RoleApi
from swagger_client.api.user_api import UserApi
# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.all_permission_resp import AllPermissionResp
from swagger_client.models.change_group_products_req import ChangeGroupProductsReq
from swagger_client.models.change_publish_status_products_req import ChangePublishStatusProductsReq
from swagger_client.models.create_group_req import CreateGroupReq
from swagger_client.models.create_product_req import CreateProductReq
from swagger_client.models.create_role_req import CreateRoleReq
from swagger_client.models.create_user_req import CreateUserReq
from swagger_client.models.customer import Customer
from swagger_client.models.delete_customer_req import DeleteCustomerReq
from swagger_client.models.delete_group_req import DeleteGroupReq
from swagger_client.models.delete_products_req import DeleteProductsReq
from swagger_client.models.delete_role_req import DeleteRoleReq
from swagger_client.models.delete_user_req import DeleteUserReq
from swagger_client.models.detail import Detail
from swagger_client.models.edit_desc_customer_req import EditDescCustomerReq
from swagger_client.models.empty import Empty
from swagger_client.models.empty_customer import EmptyCustomer
from swagger_client.models.empty_group import EmptyGroup
from swagger_client.models.empty_product import EmptyProduct
from swagger_client.models.empty_role import EmptyRole
from swagger_client.models.exist_role_by_name_req import ExistRoleByNameReq
from swagger_client.models.get_all_permission_req import GetAllPermissionReq
from swagger_client.models.get_customer_req import GetCustomerReq
from swagger_client.models.get_product_req import GetProductReq
from swagger_client.models.get_role_req import GetRoleReq
from swagger_client.models.group import Group
from swagger_client.models.list_customer_req import ListCustomerReq
from swagger_client.models.list_customer_resp import ListCustomerResp
from swagger_client.models.list_group_req import ListGroupReq
from swagger_client.models.list_group_resp import ListGroupResp
from swagger_client.models.list_products_req import ListProductsReq
from swagger_client.models.list_products_resp import ListProductsResp
from swagger_client.models.list_role_req import ListRoleReq
from swagger_client.models.list_role_resp import ListRoleResp
from swagger_client.models.list_users_req import ListUsersReq
from swagger_client.models.list_users_resp import ListUsersResp
from swagger_client.models.permission_by_uuid_req import PermissionByUuidReq
from swagger_client.models.permission_by_uuid_resp import PermissionByUuidResp
from swagger_client.models.product import Product
from swagger_client.models.product_info import ProductInfo
from swagger_client.models.reset_password_user_req import ResetPasswordUserReq
from swagger_client.models.role import Role
from swagger_client.models.role_detail import RoleDetail
from swagger_client.models.sku_item import SkuItem
from swagger_client.models.update_group_req import UpdateGroupReq
from swagger_client.models.update_price_product_req import UpdatePriceProductReq
from swagger_client.models.update_role_req import UpdateRoleReq
from swagger_client.models.update_stock_product_req import UpdateStockProductReq
from swagger_client.models.update_user_req import UpdateUserReq
from swagger_client.models.user import User
from swagger_client.models.variation import Variation
